---
title: 'TP I: Analisis Exploratorio'
date: "2021-05-01"
output:
  html_document:
    highlight: tango
    theme: sandstone
    df_print: paged
---

# Analisis Exploratorio

## Analisis univariado

Importamos la librerias necesarias
```{r}
library(pacman)
p_load(stringi, tidyverse,  readr)
source('../lib/data-access.R')
source('../lib/plot.R')
```


Veamos las distribuciones de cada variable numérica:

### Danceability

```{r fig1, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'danceability')
p <- gplot_hist(result$danceability, name="Indice de Vailabilidad", binwidth=0.03)
ggplotly(p)
```

### Energy

```{r fig2, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'energy')
p <- gplot_hist(result$energy, name="Energy", binwidth=0.03)
ggplotly(p)
```

### Loudness

```{r fig3, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'loudness')
p <- gplot_hist(result$loudness, name="loudness", binwidth=1)
ggplotly(p)
```

### Speechiness

```{r fig4, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'speechiness')
p <- gplot_hist(result$speechiness, name="speechiness", binwidth=0.03)
ggplotly(p)
```


### Acousticness

```{r fig10, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'acousticness')
p <- gplot_hist(result$acousticness, name="acousticness", binwidth=0.03)
ggplotly(p)
```

### Instrumentalness

```{r fig5, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'instrumentalness')
p <- gplot_hist(result$instrumentalness, name="instrumentalness", binwidth=0.05)
ggplotly(p)
```

### Liveness

```{r fig6, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'liveness')
p <- gplot_hist(result$liveness, name="liveness", binwidth=0.02)
ggplotly(p)
```

### Valence

```{r fig7, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'valence')
p <- gplot_hist(result$valence, name="valence", binwidth=0.01)
ggplotly(p)
```

### Tempo

```{r fig8, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'tempo')
p <- gplot_hist(result$tempo, name="tempo", binwidth=2)
ggplotly(p)
```

### Duration (ms)

```{r fig9, fig.height = 6, fig.width = 9, fig.align = "center", include = TRUE}
result <- get_collection_fields('track_features_top_10', 'duration_ms')
p <- gplot_hist(scale(result$duration_ms), name="duration_ms", binwidth=0.3)
ggplotly(p)
```



